version: 0.2
    
phases:
  install:
    on-failure: ABORT 
    runtime-versions:
      nodejs: 18
    commands:
      - echo installing serverless
      - npm i -g serverless@3
      
  build:
    on-failure: ABORT 
    commands:
      - echo Deploying resources
      - serverless deploy --stage dev

    
artifacts:
  files:
    - my-artifact/*
    - location
  name: NotesProjectArtifact

cache:
  paths:
    - 'node_modules/**/*'
